language: node_js
node_js:
  - '8'

sudo: required

services:
  - docker

env:
  global:
    - COMMIT_SHA=${TRAVIS_COMMIT::8}
    # Use repo defined by dev3 environment
    - USE_AZURE=true
    - CLOUD_CONFIG=buildit
    # BUILDIT_SECRET
    - secure: tKwKz16WArrK/6i+entP7QBst5Gef27aRMrUgUh4Wk97rZ25o2Ucn5sdEQ1B0nt5izwGDicapFbdjZNS4oHqeV17ULz8u1B6Od7WMdlaSUZNRILUm184UVxTMTzoX0WczkTf83ee4EHW/gH32v4hhdA6JEwbZkpayn6dC/ciz4CF2tqm8i00+4RvLQPzSAMJl3uar0Q+zVUagsxl3yEoWI5mQbancVrEnWkX0EyKfJYHNOrQ/QwbFQ1Rz9LRYZH2m/5Zv8vPC3o0UU7M47OGEMIYtR3ylmDytmN2JaxgkrR8eaAEENA0HaBh1ISGjDh3viQudAgOe+8L9zna9f7Y87uTaqMUKtkihgfKzc0m3DZfXyQAcCym3PmKofkrx/soWUGrxoTW8BYwoAkOteczyk94bg4JpITpgiXVmHTGUb0hPP8gzutCi9/JFWdj5neHT1GGv9lJfIlqytOXaq5yljqOD87d7C7cKrloZyBm8MPfFFK39nSxjoPEtWyL0G7VWNdZrfuOLspXPJFbIeUigv3I0qsUoo7pt693EZTut9mb1h2cystJ6mprKhB+xoKSOaYfswsvNINhhXf0ER5ZeEuMr8kK8Ix8QYi8dDMFmgS9hGglCgaU6V2dPK0BcWFjBcvt1qqKn5KLGGHnRpI/dRXBOWeSb9Qv+vzZWqflspA=
    # DOCKER_USERNAME
    - secure: PTWChodVVHqjqwITaRorVK3aMU/v2coS1d+/hlEvKtqTMTjLMCorPGyYvOLZljwv5S8KRPfhFYwssynwc/0OyqSZB00okDscYzbdFoTVAXhGYfRaNluQcquo9c+JBYSYSGG7AZpxIE0aE5CFNhBT8yYCBWGphBfdkMSPH6R/Oj6h8b6UZfQZ4o21ZJ5SaLqZB99pjQhhTYYkXZ1TVXW8bnw86pc/snWGNyEV/8SHwzK55oFfL+2afIQFKNYFFlPDzKVBF5XX5cyGG8oP9RY/UOkDYHcdyCFuP80bFLSR+a8aNzOjAF4Ie6xRGlFmhQJZrLvgGAIO8Zqg4eFQvFemEM3iEwK6i6l+8wzUj9lu/cTLTqV8aLMOAbcH0KfDPkYTK11OkZpiBpAPfh+BqEY1+ID14nVt+AOlV7PnB6pKKVpNk3Ek8GX/he9pAhYdrbfETaVM6xx4V2heR/tu4MvEfZkfqEsJImy9y6VudHhMhEK76fNX+C4ZsKQFEk4VuAbshaGnDuWKyxtd/XsVBBJioFhwYBYXLeiLeOE07JfMNBM+ViTaMoSC1i9+xL7jt5bBWD/s4GOwW3v4NSRoDuDNYGEc139FIUxbtRsIVty+m8vJNZIJqT7+3mUWhWIa1G5c00IDSvaIOc0BdwH6OFv02/vQbYgj03n36xWtPEOEF6A=
    # DOCKER_PASSWORD
    - secure: VBJmdo89idFJRprW1M+FQm0XkZAj351TOauufz/BSRYeEJ5kVDKkfuywFW2/L1GnG77hU9aJ+U13pZDZW1GCX15JiG+x/bH5hmbcOLl9HJTcijJzrpSeZtuCqI5LRRLjeY2mbj2HyE6EoSxHf17gwL31LJvEkNAr4WR7MAcuov5MxExnunIlP+tAoqqUU5h5yf0VTKZm51haNCRYoTFn5NJKgbUirCtkREFks4d3vKUcKg81nJDhLCtfg7o2up+2URO4WO+njoRrL5doCxQ3pal89gaLIop3i21G2ul8NXaafSsCSbXSoe2LxdrIr9Scugwpe+VV8FE/1+KczFdSlb81bK5pECN7JhubljRUhUqcfE2xRApxNcez4v3G8KC8MDt2Z3VUdffFPw192H3G/WM0CE/7HWoRSgKDyEu6m2SXdFo9Pk0OIVoFJ+9azGtbvHBhqPl6dOZzPHPOh0fWGCw1MTWcnvree5uKfdEcJ50E7PMWjIiCgZkjabKyBEadlhK73pxp+m5oNgzYUfRr6/YEnHTExzEmWdydT2jUNoZB/51JCsj1dxL8Islo11+Jwc5uuRS5zv6gnuvHBQaHJkOdZe+jtxMZbmDwdHIvQ93jtckuk5GKjOS1Dn+dTjGmgvbeJfnDLk/BsZXdTS15txTtjweXpYxHFaXOadtpxJs=
    - AWS_DEFAULT_REGION=us-east-1
    - ECS_REPO=hap-bookit-hap-dev-server-ecr-repo
    - ECS_CLUSTER=hap-bookit-hap-dev-ECSCluster
    - ECS_SERVICE=hap-bookit-hap-dev-app-BookitServerService-1G0GQYFT7FZ7-Service-LAF362KJLI9J
    # AWS_ACCESS_KEY_ID (CloudFormation stack IAM account)
    - secure: CObJL1ao1XulqqeVROJhmzrJgNZ87xZSMzjEBeUOyviDKixhRaXy0DOfyTOmtPSGBLY8xSw0JH+YheSrVv/t1iAdzETEFKl+lZHNS5oBa+eeIzXwhTfpyN8RdQAqFoMK5WRta9yj4Ut7bWUfDb2lv7+QcNRWsQVQ5mvvF1FK0c+6xnjILuu2CD3ziuwQRa2/lPWrVmGUHiWIHd5ljrt9cmwFmesxnLLXz64tXZU2yyK4lxZr42bqdZqmS3GAkazPSlpabqbpdepy+AVzQ3qm8tY3altqqx4iVfC7Sck66fNFN9mKyRB6CCSH1LBVgP60MujnFbAjFXHPc9ajEy7XT8XygPI1PQ2pRDkGLeqAGoXbHsNRkMmgrori0fJayhX4HiMOGVcLNwcr1tvI63liTSH/hCnE51DDpPG3plYiOycCKf2lSJlg7bCEUpZ6uVxnrC5QZIytRj24Vg3qf7JxQ6yrEl7QI1TQitHeJf+bi0E1Oer2CkB06gUQSPcHoygk02VoBFGdoksut6N0pcK6XJ+DHjLbrQukGrRySEY2mPPQkVoEZhvxJx/vzcz3AFbLNiMXXKeLJTKW2BSJ2KcSUeMBiZfoCPp50xEvIh7xGF04Zi+Zm5fjlYtY5I6Z/gF2spEy6A2PUbWbaRvBFEPI4fgVkEqCnFp+e4BuP5ACyNs=
    # AWS_SECRET_ACCESS_KEY (CloudFormation stack IAM account)
    - secure: kY5Yrn7CzUHrwTptv5hM4rk/yDKO+7BY9VW3UHF23bjRf/gFcDRw8Va7zo0HOANTo89cv8eUg3JwvsHkP30VK+VeR8YpztLziTxn+ghcW/DZejrcQ4Aj2S1TNT23p/Io1l6P1vWcOyCCj+OK8S1e8rzjWYu5MLhvRomwI9Z/fowg2bdh5dA1bSWhBG7Juzb6xIOdbjt2xRqIDRl8SsmM/gvwBPIEVJsxLib9Gb+ns0dKAEFGWwcquK7s2QZYev1BVi6xTLUBbVTqKPZVG5yWn2+izzcF2xOd++R2hCtqDatPPbT2pluxF7NWE7hFSkBfeNvVwFzl8aPnrdpfoQ6xg8OuvybNdbzy8diI6iIrQ8K2dA6L+gPl4F8HvvFoqvSeq2N3xqTf8NGU1RBkOyjao3IxlijS9cmXVIhrIsoz9YE9BsxwMrZqSRT7cyFJuKJUc6GrEt2O71DYazWV2LSBM/LLlie+RpJSMMbIaZh/ixyihgGVWizFVvkPNJ1pCQ/pWlOjmzsm+eBMy1RNgBXQeGk/iCSL19wjQcN7XsFXZW5GsHgoPve3zgfk9T+lwlj2WMVicGXAhe0YdSXdLYYgrAlWfGBm4Qy6apvyybXZLokkdh/Ok+Ye44ektHu7nzjqjAWeb6Su09SpTP45YCpbEpN5O0LXzh8DbhiUzQOcYI0=

script:
  - npm test

deploy:
  - provider: script
    skip_cleanup: true
    script: ./scripts/build-and-deploy.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ./scripts/get-deployment-scripts.sh
    on:
      branch: 33-deploy-to-ecs
  - provider: script
    skip_cleanup: true
    script: ./scripts/push-to-ecr.sh
    on:
      branch: 33-deploy-to-ecs
  - provider: script
    skip_cleanup: true
    script: ./scripts/ecs-deploy.sh -c ${ECS_CLUSTER} -n ${ECS_SERVICE} -i 006393696278.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECS_REPO}
    on:
      branch: 33-deploy-to-ecs

notifications:
  slack:
    secure: RaG5mPx+GHLh1bvfUUEyyTBw8E+qQebkdj4gKLFWEnNZA2bn2UErrXjyjBF7Ta3ATXN+DtdLdOGKLeTwyJpha+XHGmvwPIySVrQolnD+0wHP7KtmcD4wI4WxVlG4lSR3ctuC0cNe64pB/2ZxwmhSCr/ziFxXtz4QeDozkh+s6DR0/a4RUNjdrUgcGwqpL4BsbPgTAtuupKtcArbggzymIBGmulz+4Bvr+scWsVpN/5TlAI8iXT+9Utr8n/QdKFZBTC4NDPaR5hBvYgh/+M1esKZy0LGedgHa1oNRIwrWzciLXB7/jrQHEJWU87zGmeHl4Kh7cmLQ6Oj/2fr5xPBLuVqWpOLKpwe2+IFvfrN6DIp1jnpvqa9e1gSMBw8WTnzY046a1On7pWn3eglsHB4oK1nJn/8h5o+DqOoTrHsFs1vjUWx/Fcs9L8cMtI4EVgK82O1oWvl1g2s3hV1EWIm3IJaDPGxUXU8H+RrVf6UPrQsyIbJUBX4iRMjOOLjed63mF4VTnIINn+oo/0d4v1ldPhjkqSvZeqkNOik5uMjTQ7iOfz5fSdMTDz4JBaTkg69SX6ep2K7EOFXI3GiBel/9CaQCE2uAwiFdZs3ogk92XWOZmwVlig0itoAYLrzFIvEqy8WoMHXyeSLvRXuCRenLXROOM8M9a4dh6koAIQAhz9k=


