language: node_js
node_js:
  - '8'

sudo: required

services:
  - docker

env:
  global:
    - COMMIT_SHA=${TRAVIS_COMMIT::8}
    - USE_AZURE=true
    - CLOUD_CONFIG=buildit
    # BUILDIT_SECRET
    - secure: tKwKz16WArrK/6i+entP7QBst5Gef27aRMrUgUh4Wk97rZ25o2Ucn5sdEQ1B0nt5izwGDicapFbdjZNS4oHqeV17ULz8u1B6Od7WMdlaSUZNRILUm184UVxTMTzoX0WczkTf83ee4EHW/gH32v4hhdA6JEwbZkpayn6dC/ciz4CF2tqm8i00+4RvLQPzSAMJl3uar0Q+zVUagsxl3yEoWI5mQbancVrEnWkX0EyKfJYHNOrQ/QwbFQ1Rz9LRYZH2m/5Zv8vPC3o0UU7M47OGEMIYtR3ylmDytmN2JaxgkrR8eaAEENA0HaBh1ISGjDh3viQudAgOe+8L9zna9f7Y87uTaqMUKtkihgfKzc0m3DZfXyQAcCym3PmKofkrx/soWUGrxoTW8BYwoAkOteczyk94bg4JpITpgiXVmHTGUb0hPP8gzutCi9/JFWdj5neHT1GGv9lJfIlqytOXaq5yljqOD87d7C7cKrloZyBm8MPfFFK39nSxjoPEtWyL0G7VWNdZrfuOLspXPJFbIeUigv3I0qsUoo7pt693EZTut9mb1h2cystJ6mprKhB+xoKSOaYfswsvNINhhXf0ER5ZeEuMr8kK8Ix8QYi8dDMFmgS9hGglCgaU6V2dPK0BcWFjBcvt1qqKn5KLGGHnRpI/dRXBOWeSb9Qv+vzZWqflspA=
    # DOCKER_USERNAME
    - secure: PTWChodVVHqjqwITaRorVK3aMU/v2coS1d+/hlEvKtqTMTjLMCorPGyYvOLZljwv5S8KRPfhFYwssynwc/0OyqSZB00okDscYzbdFoTVAXhGYfRaNluQcquo9c+JBYSYSGG7AZpxIE0aE5CFNhBT8yYCBWGphBfdkMSPH6R/Oj6h8b6UZfQZ4o21ZJ5SaLqZB99pjQhhTYYkXZ1TVXW8bnw86pc/snWGNyEV/8SHwzK55oFfL+2afIQFKNYFFlPDzKVBF5XX5cyGG8oP9RY/UOkDYHcdyCFuP80bFLSR+a8aNzOjAF4Ie6xRGlFmhQJZrLvgGAIO8Zqg4eFQvFemEM3iEwK6i6l+8wzUj9lu/cTLTqV8aLMOAbcH0KfDPkYTK11OkZpiBpAPfh+BqEY1+ID14nVt+AOlV7PnB6pKKVpNk3Ek8GX/he9pAhYdrbfETaVM6xx4V2heR/tu4MvEfZkfqEsJImy9y6VudHhMhEK76fNX+C4ZsKQFEk4VuAbshaGnDuWKyxtd/XsVBBJioFhwYBYXLeiLeOE07JfMNBM+ViTaMoSC1i9+xL7jt5bBWD/s4GOwW3v4NSRoDuDNYGEc139FIUxbtRsIVty+m8vJNZIJqT7+3mUWhWIa1G5c00IDSvaIOc0BdwH6OFv02/vQbYgj03n36xWtPEOEF6A=
    # DOCKER_PASSWORD
    - secure: VBJmdo89idFJRprW1M+FQm0XkZAj351TOauufz/BSRYeEJ5kVDKkfuywFW2/L1GnG77hU9aJ+U13pZDZW1GCX15JiG+x/bH5hmbcOLl9HJTcijJzrpSeZtuCqI5LRRLjeY2mbj2HyE6EoSxHf17gwL31LJvEkNAr4WR7MAcuov5MxExnunIlP+tAoqqUU5h5yf0VTKZm51haNCRYoTFn5NJKgbUirCtkREFks4d3vKUcKg81nJDhLCtfg7o2up+2URO4WO+njoRrL5doCxQ3pal89gaLIop3i21G2ul8NXaafSsCSbXSoe2LxdrIr9Scugwpe+VV8FE/1+KczFdSlb81bK5pECN7JhubljRUhUqcfE2xRApxNcez4v3G8KC8MDt2Z3VUdffFPw192H3G/WM0CE/7HWoRSgKDyEu6m2SXdFo9Pk0OIVoFJ+9azGtbvHBhqPl6dOZzPHPOh0fWGCw1MTWcnvree5uKfdEcJ50E7PMWjIiCgZkjabKyBEadlhK73pxp+m5oNgzYUfRr6/YEnHTExzEmWdydT2jUNoZB/51JCsj1dxL8Islo11+Jwc5uuRS5zv6gnuvHBQaHJkOdZe+jtxMZbmDwdHIvQ93jtckuk5GKjOS1Dn+dTjGmgvbeJfnDLk/BsZXdTS15txTtjweXpYxHFaXOadtpxJs=
    - AWS_DEFAULT_REGION=us-east-1
    - S3_BUCKET_BASE=rig.hap.bookit.hap-dev
    - ECS_REPO=hap-bookit-server-ecr-repo
    - INT_ECS_CLUSTER=hap-bookit-hap-dev-ECSCluster
    - INT_ECS_SERVICE=hap-bookit-hap-dev-app-BookitServerService-K58CS2TTD0MM-Service-WBC8KZRCOYVA
    - STG_ECS_CLUSTER=hap-bookit-hap-stg-ECSCluster
    - STG_ECS_SERVICE=hap-bookit-hap-stg-app-BookitServerService-2O3Q4C6YW3EB-Service-9ZPUVY0TAIDM
    # AWS_ACCESS_KEY_ID (CloudFormation stack IAM account)
    - secure: bGqCbLymNx9yUrVyYGZ/8NCyteCSDZbgFMASJIoWi09c6yJwm7GjO8gHnmATAuv/jZ0S+DLZDQOCe+4IH65lnQwrJvwTTEhvXrhVygcw/m8z0oKTyFk/GHyMRmm3zowHV0kr++nHzb6HoPowF1210s2o0WHEAP7WO+tcWawsbBVqif3g8iBQn4OU82PzwDBkmpwn8e6TEwnFJE7kUIWKYYElDrGJOd+kfZN0DBG8V5uVE7Nv4Ov4Pim7jiXnb6NwDAqBrqpXjJHjmM+gYPa7HAJUmSFGnmQK72G/3RnN/airDdHJgWjvQP4cvZncw607krnxedc0gY8TMI9QcIGZI8X9zozOtoDpbNz6QbCUm0yMSXJJagO1kRDmewoXsvGrAUvSBQMIIXK5rGDUKh6SwcTjI6sRNO4PpsQxYZjGn9MC0jR73rhX8Bnk6gU6pY+54DGRA/YZ0XH8+eAZE9Ppcqg46eMYRHGhOYS4fCo9Px0jvTgsL7wxaqD2VBWx8Jh4dRVPHwdiNJdrvK8IJvmOxe1hmNjUHzoRo6WR+u5R37PImnR8rigPmJcvzxlFirkckXcx4sdO0688+h3tc/POkKdC6G0RJ9bj7AKsdxVnInZc36DeJsAPDE5n/T+46prjfm4NGmBXzPLmRVGFohTdKNpKvI4FNGAPy5UizHTDcDg=
    # AWS_SECRET_ACCESS_KEY (CloudFormation stack IAM account)
    - secure: ktqH31hFf3gdwOd1BkrwyZbEu2MJ9pbPVZM/T8BfAD5Eoy6yNXDN7YyRrkvbkiDh+6ncs6Ma/KohdbGk9iFxLT5J6lKZjB/Z4LUC71Bjsw+r41wjxAOoEGvepjKpqvo5jIA1Rl0+fOU35/2BlAOpZLd+m/qvyREv4nCyjfDd5pdDmKfqZTaWgvAI+UGgUsDyJHWKeiGlfhlYGoyavMOcv9V2dPetzN0+89Z6Uf0J2fQSE76vHtHAoO9Kz/ZVxWujHKNkCvOiuB57wHqTe5YzAKVvb4Vzt/LxMGHvIu5v0ZQaeZ9ze3PgUw8PnE3xkE+RaqaracuboI3GioOjxXY6CsAZy1K6TVb7Ca4Tdhcbqui59hT52fCaB+KX22d2C4f0orF2SUHjy9UhEpm5yqD4qbxbhMpQHmOJ5SSMlAOdypw7hQNHGgcwi5ZCGfskS/3yxWidDnby8PrCMEQK7oUAfNILSt2CZeVud+LKbEwhuJy6bvAsD5OCOidcOX9LWe2pmjmU+SPsrECN8w2zRXe1u/7GFuSW+40KCzQwGVqtp6Q9/lHQH5Jf0xgLqqX0zDigKgwxambLWoLSwXGTO6AmompkqH2B5J1xEAl1R63ipiU/h3DDJ/zOfejS5HEYw+dPqGvB5taFyvadDJq5MEYBxoQSmf9vsv8UMdYMXG0SHEI=

install:
  - if [[ -z "$TRAVIS_PULL_REQUEST" || $TRAVIS_PULL_REQUEST == "false" ]] && [[ -z "$TRAVIS_BRANCH" || $TRAVIS_BRANCH == "77-bookit-server-run-in-staging" ]]; then pip install --user awscli; fi

script:
  - npm run build
  - npm run test:unit
  - ./scripts/get-deployment-scripts.sh
  - ./scripts/push-to-ecr.sh
  - if [[ -z "$TRAVIS_PULL_REQUEST" || $TRAVIS_PULL_REQUEST == "false" ]] && [[ -z "$TRAVIS_BRANCH" || $TRAVIS_BRANCH == "77-bookit-server-run-in-staging" ]]; then ./scripts/run-ci-cd.sh; fi

notifications:
  slack:
    secure: RaG5mPx+GHLh1bvfUUEyyTBw8E+qQebkdj4gKLFWEnNZA2bn2UErrXjyjBF7Ta3ATXN+DtdLdOGKLeTwyJpha+XHGmvwPIySVrQolnD+0wHP7KtmcD4wI4WxVlG4lSR3ctuC0cNe64pB/2ZxwmhSCr/ziFxXtz4QeDozkh+s6DR0/a4RUNjdrUgcGwqpL4BsbPgTAtuupKtcArbggzymIBGmulz+4Bvr+scWsVpN/5TlAI8iXT+9Utr8n/QdKFZBTC4NDPaR5hBvYgh/+M1esKZy0LGedgHa1oNRIwrWzciLXB7/jrQHEJWU87zGmeHl4Kh7cmLQ6Oj/2fr5xPBLuVqWpOLKpwe2+IFvfrN6DIp1jnpvqa9e1gSMBw8WTnzY046a1On7pWn3eglsHB4oK1nJn/8h5o+DqOoTrHsFs1vjUWx/Fcs9L8cMtI4EVgK82O1oWvl1g2s3hV1EWIm3IJaDPGxUXU8H+RrVf6UPrQsyIbJUBX4iRMjOOLjed63mF4VTnIINn+oo/0d4v1ldPhjkqSvZeqkNOik5uMjTQ7iOfz5fSdMTDz4JBaTkg69SX6ep2K7EOFXI3GiBel/9CaQCE2uAwiFdZs3ogk92XWOZmwVlig0itoAYLrzFIvEqy8WoMHXyeSLvRXuCRenLXROOM8M9a4dh6koAIQAhz9k=


