language: node_js
node_js:
env:
  global:
  - COMMIT_SHA=${TRAVIS_COMMIT::8}
  - DOCKER_REPO=bookit-server
  - USE_CLOUD=true
  - CLOUD_CONFIG=buildit
  - secure: UvTNvw3SU46B1c9oLjvJSgS3+AdwBa3ajNYwctO3fflBbDuuIfsYaFOan9CHrq1Nbtmn1Wg9SOXKr8eeqpYyw7xbSgtW7ZGY0+0gMEBA6QXeSbTOFjBEiyPU7YdVx8grUDwAKAK08QczLDeOSVoJ1vf9CzEFMU2T3QnTUMf9VUT/hSVxoIwWVVAQTeaBOrc27xmvI58aReuR8qLJvRbOQAYjguAqnhc/7iY79AUVVCOqUueJGftQ6bdRsP/KVMD5SQZpVhqOV7SzFS7LN6DSaY9iA5/LCd046d6zRA2OvWKt65pwu1Mp9USpLO5Naoyf8NzqlMactqmRP74v4nDEC/2haZD2I9gdF0wgGhwrm8kgDUAwU9C3P1DHFdPiP+WPgV1rEuoBbWH6L1sB+GXpTZ6md9sbrCanhnPQsiUrdE4th7Y6XPmut20DThWX5w85Y1+f9nZEUfr5fdl2Anl18N8s9oTbON9LBREOpyxRX4bPONE9aWua/xZLcKRtMpIZiTvHgwPUC4X8r3hHkF66jtjSksZL593dRNEPzjMLjlFXm6AuhlghorKlme6qFsZQswOwE91k+0VWLPElA8jiulRsmqroNF7b9fKYknG3RuOxL0DxXRdYCWqGbSGTutksRJ0DrPwseX347RLyV9a7a2Io+KF0us6zHkpSTeaN18M=
  - secure: PTWChodVVHqjqwITaRorVK3aMU/v2coS1d+/hlEvKtqTMTjLMCorPGyYvOLZljwv5S8KRPfhFYwssynwc/0OyqSZB00okDscYzbdFoTVAXhGYfRaNluQcquo9c+JBYSYSGG7AZpxIE0aE5CFNhBT8yYCBWGphBfdkMSPH6R/Oj6h8b6UZfQZ4o21ZJ5SaLqZB99pjQhhTYYkXZ1TVXW8bnw86pc/snWGNyEV/8SHwzK55oFfL+2afIQFKNYFFlPDzKVBF5XX5cyGG8oP9RY/UOkDYHcdyCFuP80bFLSR+a8aNzOjAF4Ie6xRGlFmhQJZrLvgGAIO8Zqg4eFQvFemEM3iEwK6i6l+8wzUj9lu/cTLTqV8aLMOAbcH0KfDPkYTK11OkZpiBpAPfh+BqEY1+ID14nVt+AOlV7PnB6pKKVpNk3Ek8GX/he9pAhYdrbfETaVM6xx4V2heR/tu4MvEfZkfqEsJImy9y6VudHhMhEK76fNX+C4ZsKQFEk4VuAbshaGnDuWKyxtd/XsVBBJioFhwYBYXLeiLeOE07JfMNBM+ViTaMoSC1i9+xL7jt5bBWD/s4GOwW3v4NSRoDuDNYGEc139FIUxbtRsIVty+m8vJNZIJqT7+3mUWhWIa1G5c00IDSvaIOc0BdwH6OFv02/vQbYgj03n36xWtPEOEF6A=
  - secure: VBJmdo89idFJRprW1M+FQm0XkZAj351TOauufz/BSRYeEJ5kVDKkfuywFW2/L1GnG77hU9aJ+U13pZDZW1GCX15JiG+x/bH5hmbcOLl9HJTcijJzrpSeZtuCqI5LRRLjeY2mbj2HyE6EoSxHf17gwL31LJvEkNAr4WR7MAcuov5MxExnunIlP+tAoqqUU5h5yf0VTKZm51haNCRYoTFn5NJKgbUirCtkREFks4d3vKUcKg81nJDhLCtfg7o2up+2URO4WO+njoRrL5doCxQ3pal89gaLIop3i21G2ul8NXaafSsCSbXSoe2LxdrIr9Scugwpe+VV8FE/1+KczFdSlb81bK5pECN7JhubljRUhUqcfE2xRApxNcez4v3G8KC8MDt2Z3VUdffFPw192H3G/WM0CE/7HWoRSgKDyEu6m2SXdFo9Pk0OIVoFJ+9azGtbvHBhqPl6dOZzPHPOh0fWGCw1MTWcnvree5uKfdEcJ50E7PMWjIiCgZkjabKyBEadlhK73pxp+m5oNgzYUfRr6/YEnHTExzEmWdydT2jUNoZB/51JCsj1dxL8Islo11+Jwc5uuRS5zv6gnuvHBQaHJkOdZe+jtxMZbmDwdHIvQ93jtckuk5GKjOS1Dn+dTjGmgvbeJfnDLk/BsZXdTS15txTtjweXpYxHFaXOadtpxJs=
  # AWS_ACCESS_KEY_ID
  - secure: bTubxyQPM/NJr5zX3TY03e1PEGOADTB5DJsfKKbemI5F6HoFhNip91ZAQOdzjFNejofiC7llXoiQ8t674MAcXyXpLvK8lFZo+oVfkvntJ+onFWdKClC+enXStqhQkelaUHnaCd0xxIK3ZEpRoeyUayFssYAWgmTIF07PgH1J2BEECuw4m9iMJuAFiTRUjAXsI0GXhvV0P0N9JpcgH6g9RVaEF5ghd3Q6dmgh7aDZaVs/ufDYbuUd32zywhSZiV0nFZ5N9PbOkMujU/LeXTjecrVW3NB1Yr/R2KVRlsQp4S0LM4PEzzN3DVYeCRwI6icoB3VuS80yoVlb8cj50O6sOtRlbG6wjVOxSXoKH/KtUKEOYcPcbQiMNZQeWUIsBXZYvepE557Jv7nvRraekdaYUvyWjyaxrLJWzHrheJ2vY3T039n8Yf93DJqVs1Ic8AmuosAK2eKdYUNNTxrd5r9qbBW2pD16J9yBBYL5RjvG98hGdxrGBjW0DoZ5+FgZa9KxECzVuygTep55y2jRvZWThBE3+LQ0nai2QKp5dOa7NBMqpWvqptQTm+Zsd/G6TWhZTA+yEDZMAvdnYxCDPzuphiUE++41xkvOnIw7uVuQvq2nEHw9QBdc1CE+S3tg4WJrLvgffWZickuRkDJZxEt9CPPLU3aRvG+iMToA7KM2AXo=
  # AWS_SECRET_ACCESS_KEY
  - secure: N0277TJFhg/6l5Q9bbRH5btNm0WZtfRXsYo97RoZ5DK/g06vSPltceY41z5MNueF5EprtQLqV9qTijBDEXwovDZKahYisthQ6DXukbQxgrAWxeGgr+hhu8iDH2CgHuQMlxotJ4pRwd0SljNXiiWdPM1rdgW4D6yPGBuBpFjrqvILT8M1ubXOcfwvL96TaOky+F1FXIt8DzVVUppvpNyoNBwWqz4Bw+9HjxyILXQJ2IL9X4TnPYu91MGt7XUGEL4BKneMJQfzvqyt2WOHXzv3zCQUUmXMZGAySMhQrTInyY30HnR/NsNgXjCsilPzO6T1J23oS6thI+eKXlNRCpyiGKQHAmrKsAxJjkYC4kBOo86wCONToZQUDluUxJaSr8FbwUclmBEIktIPEWv4neuoGp/SW+zTDz39Ma6n4+FExIIOZzW7uSNarMM1+iUXc6pXywGLh/kTvZGT2l3BhJ3WUs8Y7WiLWdRFblORo0ChV48DgqaEgjfJ/U0WYpO6hLZcCCWX/DvYqFY7BoxgAxoeCtIEsJOIBZyCIDs9UOQUH3uZCUoSxUVxul3P6/8RIE+7Riotcrd9Nue6fURpUOHnVjutXgvRxleqK1FwvtaoRuKJgYje4UOtC5os5/MVXyKJ5mU5gVMB2tlSq9Skiz5KA7eYpy3KYhoUFCCdYAdtAgU=

notifications:
  slack:
    secure: RaG5mPx+GHLh1bvfUUEyyTBw8E+qQebkdj4gKLFWEnNZA2bn2UErrXjyjBF7Ta3ATXN+DtdLdOGKLeTwyJpha+XHGmvwPIySVrQolnD+0wHP7KtmcD4wI4WxVlG4lSR3ctuC0cNe64pB/2ZxwmhSCr/ziFxXtz4QeDozkh+s6DR0/a4RUNjdrUgcGwqpL4BsbPgTAtuupKtcArbggzymIBGmulz+4Bvr+scWsVpN/5TlAI8iXT+9Utr8n/QdKFZBTC4NDPaR5hBvYgh/+M1esKZy0LGedgHa1oNRIwrWzciLXB7/jrQHEJWU87zGmeHl4Kh7cmLQ6Oj/2fr5xPBLuVqWpOLKpwe2+IFvfrN6DIp1jnpvqa9e1gSMBw8WTnzY046a1On7pWn3eglsHB4oK1nJn/8h5o+DqOoTrHsFs1vjUWx/Fcs9L8cMtI4EVgK82O1oWvl1g2s3hV1EWIm3IJaDPGxUXU8H+RrVf6UPrQsyIbJUBX4iRMjOOLjed63mF4VTnIINn+oo/0d4v1ldPhjkqSvZeqkNOik5uMjTQ7iOfz5fSdMTDz4JBaTkg69SX6ep2K7EOFXI3GiBel/9CaQCE2uAwiFdZs3ogk92XWOZmwVlig0itoAYLrzFIvEqy8WoMHXyeSLvRXuCRenLXROOM8M9a4dh6koAIQAhz9k=
sudo: required
services:
- docker

script:
- npm test
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_EVENT_TYPE" == "push" ]; then
    export IMG_VERSION=`node -p -e "require('./package.json').version"`;
    echo "Building $IMG_VERSION";
    npm prune --production;
    docker build -t builditdigital/bookit-server:$IMG_VERSION .;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push builditdigital/bookit-server:$IMG_VERSION;
    docker tag builditdigital/bookit-server:$IMG_VERSION builditdigital/bookit-server:latest;
    docker push builditdigital/bookit-server:latest;
  fi

deploy:
  - provider: script
    skip_cleanup: true
    script: chmod 600 ./deploy/ec2/travis && ./deploy/deploy.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: AWS_REGION=us-east-1 ./scripts/build-aws-ecr.sh
    on:
      branch: aws-ecr-push-server

# Decrypt deployment key
before_install:
- openssl aes-256-cbc -K $encrypted_2d5b9f764c04_key -iv $encrypted_2d5b9f764c04_iv -in ./deploy/ec2/travis.enc -out ./deploy/ec2/travis -d
