language: node_js
node_js:
- '7'
env:
  global:
    - USE_CLOUD=true
    - secure: "UvTNvw3SU46B1c9oLjvJSgS3+AdwBa3ajNYwctO3fflBbDuuIfsYaFOan9CHrq1Nbtmn1Wg9SOXKr8eeqpYyw7xbSgtW7ZGY0+0gMEBA6QXeSbTOFjBEiyPU7YdVx8grUDwAKAK08QczLDeOSVoJ1vf9CzEFMU2T3QnTUMf9VUT/hSVxoIwWVVAQTeaBOrc27xmvI58aReuR8qLJvRbOQAYjguAqnhc/7iY79AUVVCOqUueJGftQ6bdRsP/KVMD5SQZpVhqOV7SzFS7LN6DSaY9iA5/LCd046d6zRA2OvWKt65pwu1Mp9USpLO5Naoyf8NzqlMactqmRP74v4nDEC/2haZD2I9gdF0wgGhwrm8kgDUAwU9C3P1DHFdPiP+WPgV1rEuoBbWH6L1sB+GXpTZ6md9sbrCanhnPQsiUrdE4th7Y6XPmut20DThWX5w85Y1+f9nZEUfr5fdl2Anl18N8s9oTbON9LBREOpyxRX4bPONE9aWua/xZLcKRtMpIZiTvHgwPUC4X8r3hHkF66jtjSksZL593dRNEPzjMLjlFXm6AuhlghorKlme6qFsZQswOwE91k+0VWLPElA8jiulRsmqroNF7b9fKYknG3RuOxL0DxXRdYCWqGbSGTutksRJ0DrPwseX347RLyV9a7a2Io+KF0us6zHkpSTeaN18M="
