language: node_js
node_js:
  - "7"
env:
  global:
    secure: kGQcT8auGhf/+RHK6AV1Zaa0g+LJQT/ZFeGBruQGjQvcKgFFKBIXGCdfuPG4F/44eLhoa7XJYo6eag+whd00T95jUq4UBmODrZHLE7ntiPp7hBtK4y00h5p9nOwU6WyAK6Qn2WC3OQAHWdUCb+o9b9PBhN9Pk4e/Btxmn7KwLGNY1LpWCf1XkVMi4rubgyAFUykDbg8cGE9DsupO6+Evm4Zy7IBYalVmboA3zDh5B1TnTlKsS1s1YC5j3wcT2r4kwIKkkRddsaZGT5UKBWy01oH8YWDtvcvPGuxunPHzeDlg+gGVYKdOThwe8A7YAGNRRusHbeU5z/laTaEJEzBlFaHUJ1iwPP3o7wllCh2BrZKOguqedciEpVAYkCYG0VKwk9I9OyeSsXREkBhnHFwRMn396/BkxW5tUSRIBLiavfELoGvx1EOakx+Io4YifbXwS22jA3y1kIQFsNt8y7sIiGrlXP100TTSMMpFNK/cP7eNzZMKMawlhDupNtp3w4J9QQHZs6fUj/9jHIF9YgRex13PnjSngB1SeQk8rQUKjmeUXTpCb5oMGmsxKF0qhPL1HIXqipxYggpwU4wr6jkeU/c+j0QW3Hb4YqZjmWwqkB40HhWtO9pcMa1o4WkwRgRDCJ+3sanvZoYeQ5pULIMYFY0ZLUEkPz8C7y4RySQMIdA=
