language: node_js
node_js:
  - '8'

sudo: required

services:
  - docker

env:
  global:
    - COMMIT_SHA=${TRAVIS_COMMIT::8}
    # Use repo defined by dev3 environment
    - USE_CLOUD=true
    - CLOUD_CONFIG=buildit
    - secure: UvTNvw3SU46B1c9oLjvJSgS3+AdwBa3ajNYwctO3fflBbDuuIfsYaFOan9CHrq1Nbtmn1Wg9SOXKr8eeqpYyw7xbSgtW7ZGY0+0gMEBA6QXeSbTOFjBEiyPU7YdVx8grUDwAKAK08QczLDeOSVoJ1vf9CzEFMU2T3QnTUMf9VUT/hSVxoIwWVVAQTeaBOrc27xmvI58aReuR8qLJvRbOQAYjguAqnhc/7iY79AUVVCOqUueJGftQ6bdRsP/KVMD5SQZpVhqOV7SzFS7LN6DSaY9iA5/LCd046d6zRA2OvWKt65pwu1Mp9USpLO5Naoyf8NzqlMactqmRP74v4nDEC/2haZD2I9gdF0wgGhwrm8kgDUAwU9C3P1DHFdPiP+WPgV1rEuoBbWH6L1sB+GXpTZ6md9sbrCanhnPQsiUrdE4th7Y6XPmut20DThWX5w85Y1+f9nZEUfr5fdl2Anl18N8s9oTbON9LBREOpyxRX4bPONE9aWua/xZLcKRtMpIZiTvHgwPUC4X8r3hHkF66jtjSksZL593dRNEPzjMLjlFXm6AuhlghorKlme6qFsZQswOwE91k+0VWLPElA8jiulRsmqroNF7b9fKYknG3RuOxL0DxXRdYCWqGbSGTutksRJ0DrPwseX347RLyV9a7a2Io+KF0us6zHkpSTeaN18M=
    - secure: PTWChodVVHqjqwITaRorVK3aMU/v2coS1d+/hlEvKtqTMTjLMCorPGyYvOLZljwv5S8KRPfhFYwssynwc/0OyqSZB00okDscYzbdFoTVAXhGYfRaNluQcquo9c+JBYSYSGG7AZpxIE0aE5CFNhBT8yYCBWGphBfdkMSPH6R/Oj6h8b6UZfQZ4o21ZJ5SaLqZB99pjQhhTYYkXZ1TVXW8bnw86pc/snWGNyEV/8SHwzK55oFfL+2afIQFKNYFFlPDzKVBF5XX5cyGG8oP9RY/UOkDYHcdyCFuP80bFLSR+a8aNzOjAF4Ie6xRGlFmhQJZrLvgGAIO8Zqg4eFQvFemEM3iEwK6i6l+8wzUj9lu/cTLTqV8aLMOAbcH0KfDPkYTK11OkZpiBpAPfh+BqEY1+ID14nVt+AOlV7PnB6pKKVpNk3Ek8GX/he9pAhYdrbfETaVM6xx4V2heR/tu4MvEfZkfqEsJImy9y6VudHhMhEK76fNX+C4ZsKQFEk4VuAbshaGnDuWKyxtd/XsVBBJioFhwYBYXLeiLeOE07JfMNBM+ViTaMoSC1i9+xL7jt5bBWD/s4GOwW3v4NSRoDuDNYGEc139FIUxbtRsIVty+m8vJNZIJqT7+3mUWhWIa1G5c00IDSvaIOc0BdwH6OFv02/vQbYgj03n36xWtPEOEF6A=
    - secure: VBJmdo89idFJRprW1M+FQm0XkZAj351TOauufz/BSRYeEJ5kVDKkfuywFW2/L1GnG77hU9aJ+U13pZDZW1GCX15JiG+x/bH5hmbcOLl9HJTcijJzrpSeZtuCqI5LRRLjeY2mbj2HyE6EoSxHf17gwL31LJvEkNAr4WR7MAcuov5MxExnunIlP+tAoqqUU5h5yf0VTKZm51haNCRYoTFn5NJKgbUirCtkREFks4d3vKUcKg81nJDhLCtfg7o2up+2URO4WO+njoRrL5doCxQ3pal89gaLIop3i21G2ul8NXaafSsCSbXSoe2LxdrIr9Scugwpe+VV8FE/1+KczFdSlb81bK5pECN7JhubljRUhUqcfE2xRApxNcez4v3G8KC8MDt2Z3VUdffFPw192H3G/WM0CE/7HWoRSgKDyEu6m2SXdFo9Pk0OIVoFJ+9azGtbvHBhqPl6dOZzPHPOh0fWGCw1MTWcnvree5uKfdEcJ50E7PMWjIiCgZkjabKyBEadlhK73pxp+m5oNgzYUfRr6/YEnHTExzEmWdydT2jUNoZB/51JCsj1dxL8Islo11+Jwc5uuRS5zv6gnuvHBQaHJkOdZe+jtxMZbmDwdHIvQ93jtckuk5GKjOS1Dn+dTjGmgvbeJfnDLk/BsZXdTS15txTtjweXpYxHFaXOadtpxJs=
    - AWS_DEFAULT_REGION=us-east-1
    - ECS_REPO=bookit-dev3-mthomas-app-bookit-ecr-repo
    - ECS_CLUSTER=bookit-dev3-mthomas-app-bookit-ECSCluster
    - ECS_SERVICE=bookit-dev3-mthomas-app-bookit-BookitServerService-1TOTI1CH7GA93-Service-1H96WYF8NF5Q8
    # AWS_ACCESS_KEY_ID (buildit.bookit.travis IAM account)
    - secure: Ep0FrO6Enx67YzCG5t1C5E9af2pfuBWNgjgvFNm5jCgyO7p1PZpxIJntEyA9gcDQ+WSACxJQEWbBF2MeJ3KS6k7fkArNSRF8hS5mTL7zH0RU8yhTxVA4wXROidRdcvnwDFKn+48fS7uV6st5vhHfkxI5O/5PojOhGXQolbVOrEbniM9Hh+XOVSdAJjRFX9/N5gdtOtWPKM7jKGlprC7FBo49o0po3wLEqNRyBqpHNApv9NRp/pxwYpFcdQ+S776RVMFDbvIxjQjwwdlQqcI0uA+8EMcLWePcN0WsN97gcmlaFhtuP5vkx3miTzjaHBbRmC1VifGBAMJCB1SfgCnwsz/nKkKR7EoQnXli7cQu5Kve2frUN4ifaTMD+dBnCT3L45XyF/MLDCIKSeZYosolSyzs3RVi0qhFtpaMZZFfnj71Iilb9Bp94XTUvaQM8ID2DEBcU0UM754OBS9xyGOwTXvsdLLo0Guo0QHLEam5G6Ks+zRarROlp7901/enTSrLdJr7naerlUBcdqMScGxjgJZHLNjEyPcqpClIdoC4BYp6rKgO47CJEsR6e5/oM85t9upKnNhwrFeibxTFDNePjCWxuIHhLAdEVisdzGSJ+eebzo2RllA8qvJGlw6tWTeKW28kYOfVsgX/3BQ5zNcqhywmdEmTMQOx+fz+OwcZZgQ=
    # AWS_SECRET_ACCESS_KEY (buildit.bookit.travis IAM account)
    - secure: LjrP1fYqDjsF/a/vtt1bplCed0Q26L3NadYaveI6CG+MDwFB0n2naPUTIRXDrd4emggldv2sxCQgtJPG2ftmFOzI/G10KvrJcxZI+5cSecrHiWCn6JhANy6+ixeQUB2WRv4qRKteSvRNZWizOkciceMqErh3yvIDXcctgyzEnsjw2+qLuVfWHZf/pJ+xNzdma8/bQfgjoraMmZcHXH1psiBh6u+D4uk3fG25Ht3pg4ykD8RuLBeGtWvcaWu5Cb2ozVFMFtoSirqAuLLzxPl4RjK4RZi80Dp5BrA9mA8AdiLOJlJXP4TjfvBtTVopIMzV+oHEqL03UAM09mZw90n3ofBpUGl6O8pI0DStFNYnk8nQ9JJ5qkQXLFXSwX5YEn9ANRF1vLKKIS6ee8WTYd9gHYvh9WcoTwqgxqUKOjsXXvBmljY0XiqhqLT8zSHnWc7ZUIGgypKxLPVBOzmIwfsNWudf0FdCalp40WJMu2Hhj3QqaT/qmznIgcPFRwKcxW0Xv+Z9yD45gSJU0a45ilO9r3nirJIfVL7g6QW+Rvj8syfkwFd6zKCQ/lg2vKY7yxQgVTQqET6/661qv44R8DBB5NCkDaLuuB3tCE+2yDEYZKDvjh4RxNRARQGyL8hC3pygstpqGW6DvK3p2byBBVVJdm+ObAadGpbyXLlECLqILVQ=

script:
  - npm test

deploy:
  - provider: script
    skip_cleanup: true
    script: ./scripts/build-and-deploy.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ./scripts/build-aws-ecr.sh
    on:
      branch: 33-deploy-to-ecs
  - provider: script
    skip_cleanup: true
    script: ./scripts/ecs-deploy.sh -c ${ECS_CLUSTER} -n ${ECS_SERVICE} -i 006393696278.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECS_REPO}
    on:
      branch: 33-deploy-to-ecs

notifications:
  slack:
    secure: RaG5mPx+GHLh1bvfUUEyyTBw8E+qQebkdj4gKLFWEnNZA2bn2UErrXjyjBF7Ta3ATXN+DtdLdOGKLeTwyJpha+XHGmvwPIySVrQolnD+0wHP7KtmcD4wI4WxVlG4lSR3ctuC0cNe64pB/2ZxwmhSCr/ziFxXtz4QeDozkh+s6DR0/a4RUNjdrUgcGwqpL4BsbPgTAtuupKtcArbggzymIBGmulz+4Bvr+scWsVpN/5TlAI8iXT+9Utr8n/QdKFZBTC4NDPaR5hBvYgh/+M1esKZy0LGedgHa1oNRIwrWzciLXB7/jrQHEJWU87zGmeHl4Kh7cmLQ6Oj/2fr5xPBLuVqWpOLKpwe2+IFvfrN6DIp1jnpvqa9e1gSMBw8WTnzY046a1On7pWn3eglsHB4oK1nJn/8h5o+DqOoTrHsFs1vjUWx/Fcs9L8cMtI4EVgK82O1oWvl1g2s3hV1EWIm3IJaDPGxUXU8H+RrVf6UPrQsyIbJUBX4iRMjOOLjed63mF4VTnIINn+oo/0d4v1ldPhjkqSvZeqkNOik5uMjTQ7iOfz5fSdMTDz4JBaTkg69SX6ep2K7EOFXI3GiBel/9CaQCE2uAwiFdZs3ogk92XWOZmwVlig0itoAYLrzFIvEqy8WoMHXyeSLvRXuCRenLXROOM8M9a4dh6koAIQAhz9k=


