language: node_js
node_js:
  - '8'

sudo: required

services:
  - docker

env:
  global:
    - COMMIT_SHA=${TRAVIS_COMMIT::8}
    # Use repo defined by dev3 environment
    - USE_CLOUD=true
    - CLOUD_CONFIG=buildit
    - secure: UvTNvw3SU46B1c9oLjvJSgS3+AdwBa3ajNYwctO3fflBbDuuIfsYaFOan9CHrq1Nbtmn1Wg9SOXKr8eeqpYyw7xbSgtW7ZGY0+0gMEBA6QXeSbTOFjBEiyPU7YdVx8grUDwAKAK08QczLDeOSVoJ1vf9CzEFMU2T3QnTUMf9VUT/hSVxoIwWVVAQTeaBOrc27xmvI58aReuR8qLJvRbOQAYjguAqnhc/7iY79AUVVCOqUueJGftQ6bdRsP/KVMD5SQZpVhqOV7SzFS7LN6DSaY9iA5/LCd046d6zRA2OvWKt65pwu1Mp9USpLO5Naoyf8NzqlMactqmRP74v4nDEC/2haZD2I9gdF0wgGhwrm8kgDUAwU9C3P1DHFdPiP+WPgV1rEuoBbWH6L1sB+GXpTZ6md9sbrCanhnPQsiUrdE4th7Y6XPmut20DThWX5w85Y1+f9nZEUfr5fdl2Anl18N8s9oTbON9LBREOpyxRX4bPONE9aWua/xZLcKRtMpIZiTvHgwPUC4X8r3hHkF66jtjSksZL593dRNEPzjMLjlFXm6AuhlghorKlme6qFsZQswOwE91k+0VWLPElA8jiulRsmqroNF7b9fKYknG3RuOxL0DxXRdYCWqGbSGTutksRJ0DrPwseX347RLyV9a7a2Io+KF0us6zHkpSTeaN18M=
    - secure: PTWChodVVHqjqwITaRorVK3aMU/v2coS1d+/hlEvKtqTMTjLMCorPGyYvOLZljwv5S8KRPfhFYwssynwc/0OyqSZB00okDscYzbdFoTVAXhGYfRaNluQcquo9c+JBYSYSGG7AZpxIE0aE5CFNhBT8yYCBWGphBfdkMSPH6R/Oj6h8b6UZfQZ4o21ZJ5SaLqZB99pjQhhTYYkXZ1TVXW8bnw86pc/snWGNyEV/8SHwzK55oFfL+2afIQFKNYFFlPDzKVBF5XX5cyGG8oP9RY/UOkDYHcdyCFuP80bFLSR+a8aNzOjAF4Ie6xRGlFmhQJZrLvgGAIO8Zqg4eFQvFemEM3iEwK6i6l+8wzUj9lu/cTLTqV8aLMOAbcH0KfDPkYTK11OkZpiBpAPfh+BqEY1+ID14nVt+AOlV7PnB6pKKVpNk3Ek8GX/he9pAhYdrbfETaVM6xx4V2heR/tu4MvEfZkfqEsJImy9y6VudHhMhEK76fNX+C4ZsKQFEk4VuAbshaGnDuWKyxtd/XsVBBJioFhwYBYXLeiLeOE07JfMNBM+ViTaMoSC1i9+xL7jt5bBWD/s4GOwW3v4NSRoDuDNYGEc139FIUxbtRsIVty+m8vJNZIJqT7+3mUWhWIa1G5c00IDSvaIOc0BdwH6OFv02/vQbYgj03n36xWtPEOEF6A=
    - secure: VBJmdo89idFJRprW1M+FQm0XkZAj351TOauufz/BSRYeEJ5kVDKkfuywFW2/L1GnG77hU9aJ+U13pZDZW1GCX15JiG+x/bH5hmbcOLl9HJTcijJzrpSeZtuCqI5LRRLjeY2mbj2HyE6EoSxHf17gwL31LJvEkNAr4WR7MAcuov5MxExnunIlP+tAoqqUU5h5yf0VTKZm51haNCRYoTFn5NJKgbUirCtkREFks4d3vKUcKg81nJDhLCtfg7o2up+2URO4WO+njoRrL5doCxQ3pal89gaLIop3i21G2ul8NXaafSsCSbXSoe2LxdrIr9Scugwpe+VV8FE/1+KczFdSlb81bK5pECN7JhubljRUhUqcfE2xRApxNcez4v3G8KC8MDt2Z3VUdffFPw192H3G/WM0CE/7HWoRSgKDyEu6m2SXdFo9Pk0OIVoFJ+9azGtbvHBhqPl6dOZzPHPOh0fWGCw1MTWcnvree5uKfdEcJ50E7PMWjIiCgZkjabKyBEadlhK73pxp+m5oNgzYUfRr6/YEnHTExzEmWdydT2jUNoZB/51JCsj1dxL8Islo11+Jwc5uuRS5zv6gnuvHBQaHJkOdZe+jtxMZbmDwdHIvQ93jtckuk5GKjOS1Dn+dTjGmgvbeJfnDLk/BsZXdTS15txTtjweXpYxHFaXOadtpxJs=
    - AWS_DEFAULT_REGION=us-east-1
    - ECS_REPO=mthomas-bookit-dev6-server-ecr-repo
    - ECS_CLUSTER=mthomas-bookit-dev6-ECSCluster
    - ECS_SERVICE=mthomas-bookit-dev6-app-BookitServerService-16FGWD83CFX0I-Service-7QTKRQLFZNO5
    # AWS_ACCESS_KEY_ID (buildit.bookit.travis IAM account)
    - secure: LzH/6yoe+XwvRgD2YvraPTDPsPzdY7D9sxp98Mr+hrxwhLsZXvwOl44hwvOv0cu/zEv4gQ8Xbww6VCssSyNIysUI7GrDUYYmmDx3iBBn65X2R0Ky8/qyE0BIRwWV2PKnQQ3ppDZuotXPBaYsC8FQUa924jq9y2AsevCE1N5CgU91AufH83BoAO83ni0uVN+tCteleneVHFx1Medv5PASkM/ga/FGCxI0Sr8spQYlt/WNXXqlXPk7w3Qjj9rMHIKeZw9F/PRbUWRkSRbOEpZRba5gJGtkrue45xeR7DC8Fhc1nR0W2oStExOhCgrWICGB1x/Lu9v2ma45PfneG8LfBY37SI3Rr4141tuu96oRXuxR31bn9HcZov8Pj69QTMpPpKG0zR6ulIZOOcmRw3lhUIXTcZkSI5VXFR+Tq3ah4hxVPLdHN1Gxl8/AXxwW26RcmIRnKGZYjae249Cu8xBfbj0++J31YaprTRbF8PM+UavPwMggXe93PRVjZPn/0vv+QP2ABOoUu8FVXnKJ0Tm+Iu/ZWFcTCJk/BqiftwoC2zVzYMsRMfu81hW2/Bn9fipGT3g4Gv3MU9Qtd0CYmxRlvUCF2t5TbAaM/Be3Oqlrs6kXa6YiSRA0RYnK/FCxpADZefGNz6CU+pRTzQFtYq7tR9bNcCwA0Bo4MxA36s36dUo=
    # AWS_SECRET_ACCESS_KEY (buildit.bookit.travis IAM account)
    - secure: Zf3Hts2aLlAtlW8/J5AvYtQxNcVpvDkapZwmQXH6/sZ/TKqRJWFncIAFMTcHOBeBWx6voSnVONNdQEFHgKvuZUkCZrlaKx/+y6y8jd3tP0u5TsfqztgaeVYIxFfpt9JtpR6+C3phaIqhXq981QEqDn82dpDJv93TCY9QzucYbPxLrxj4Na9tVco35rUC6p6IbMmo7lYQCTkW6bLH56q2IHoASIWwgohZQi3XsSkJLGjsgGfqTzvUl2cxp6Gs7/kq9F25CdIVYOBHn6T7KQHp0xvXBLbHMHClPv3EcN3P/DDbX8WjMT8ztuBJqd/Ldbeg9VTZ5mbCH0W1HwVu/Fh/3x9Xl3ge30Z6Si2W6rXrS4z9JFQciTq6KWED+qa/ZfuhvceduLGsp+LMDE4JvMJg/6JiuTLwg/aqHbLRjCK3juR2F0LStHMxLBxRQgDZygyIdi6CO4GZn//g7ig4AmMm8doJjbAzIhmfi4zwFcbMqgxDhwv8p4z/oG06FjVlxokHu9p2zha7W74NuX/lx8v39TsE0VgRU7x19mVourtGk5v9ObegN2c2fKkPaDTptA+swA69s9h+N9wVHgRPF2cO+yx3oDK1EocD1jOX7WrbZZDC21CNb/ydo4rtiYQ+ecOLErcQ6weNVsrEAGvh9CLzaSoEBNsxe0bT09eXM84YQvw=

script:
  - npm test

deploy:
  - provider: script
    skip_cleanup: true
    script: ./scripts/build-and-deploy.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ./scripts/get-deployment-scripts.sh
    on:
      branch: 74-aws-integrate-web-to-api
  - provider: script
    skip_cleanup: true
    script: ./scripts/push-to-ecr.sh
    on:
      branch: 74-aws-integrate-web-to-api
  - provider: script
    skip_cleanup: true
    script: ./scripts/ecs-deploy.sh -c ${ECS_CLUSTER} -n ${ECS_SERVICE} -i 006393696278.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECS_REPO}
    on:
      branch: 74-aws-integrate-web-to-api

notifications:
  slack:
    secure: RaG5mPx+GHLh1bvfUUEyyTBw8E+qQebkdj4gKLFWEnNZA2bn2UErrXjyjBF7Ta3ATXN+DtdLdOGKLeTwyJpha+XHGmvwPIySVrQolnD+0wHP7KtmcD4wI4WxVlG4lSR3ctuC0cNe64pB/2ZxwmhSCr/ziFxXtz4QeDozkh+s6DR0/a4RUNjdrUgcGwqpL4BsbPgTAtuupKtcArbggzymIBGmulz+4Bvr+scWsVpN/5TlAI8iXT+9Utr8n/QdKFZBTC4NDPaR5hBvYgh/+M1esKZy0LGedgHa1oNRIwrWzciLXB7/jrQHEJWU87zGmeHl4Kh7cmLQ6Oj/2fr5xPBLuVqWpOLKpwe2+IFvfrN6DIp1jnpvqa9e1gSMBw8WTnzY046a1On7pWn3eglsHB4oK1nJn/8h5o+DqOoTrHsFs1vjUWx/Fcs9L8cMtI4EVgK82O1oWvl1g2s3hV1EWIm3IJaDPGxUXU8H+RrVf6UPrQsyIbJUBX4iRMjOOLjed63mF4VTnIINn+oo/0d4v1ldPhjkqSvZeqkNOik5uMjTQ7iOfz5fSdMTDz4JBaTkg69SX6ep2K7EOFXI3GiBel/9CaQCE2uAwiFdZs3ogk92XWOZmwVlig0itoAYLrzFIvEqy8WoMHXyeSLvRXuCRenLXROOM8M9a4dh6koAIQAhz9k=


