language: node_js
node_js:
- '7'
env:
  global:
  - USE_CLOUD=true
  - secure: UvTNvw3SU46B1c9oLjvJSgS3+AdwBa3ajNYwctO3fflBbDuuIfsYaFOan9CHrq1Nbtmn1Wg9SOXKr8eeqpYyw7xbSgtW7ZGY0+0gMEBA6QXeSbTOFjBEiyPU7YdVx8grUDwAKAK08QczLDeOSVoJ1vf9CzEFMU2T3QnTUMf9VUT/hSVxoIwWVVAQTeaBOrc27xmvI58aReuR8qLJvRbOQAYjguAqnhc/7iY79AUVVCOqUueJGftQ6bdRsP/KVMD5SQZpVhqOV7SzFS7LN6DSaY9iA5/LCd046d6zRA2OvWKt65pwu1Mp9USpLO5Naoyf8NzqlMactqmRP74v4nDEC/2haZD2I9gdF0wgGhwrm8kgDUAwU9C3P1DHFdPiP+WPgV1rEuoBbWH6L1sB+GXpTZ6md9sbrCanhnPQsiUrdE4th7Y6XPmut20DThWX5w85Y1+f9nZEUfr5fdl2Anl18N8s9oTbON9LBREOpyxRX4bPONE9aWua/xZLcKRtMpIZiTvHgwPUC4X8r3hHkF66jtjSksZL593dRNEPzjMLjlFXm6AuhlghorKlme6qFsZQswOwE91k+0VWLPElA8jiulRsmqroNF7b9fKYknG3RuOxL0DxXRdYCWqGbSGTutksRJ0DrPwseX347RLyV9a7a2Io+KF0us6zHkpSTeaN18M=
  - secure: PTWChodVVHqjqwITaRorVK3aMU/v2coS1d+/hlEvKtqTMTjLMCorPGyYvOLZljwv5S8KRPfhFYwssynwc/0OyqSZB00okDscYzbdFoTVAXhGYfRaNluQcquo9c+JBYSYSGG7AZpxIE0aE5CFNhBT8yYCBWGphBfdkMSPH6R/Oj6h8b6UZfQZ4o21ZJ5SaLqZB99pjQhhTYYkXZ1TVXW8bnw86pc/snWGNyEV/8SHwzK55oFfL+2afIQFKNYFFlPDzKVBF5XX5cyGG8oP9RY/UOkDYHcdyCFuP80bFLSR+a8aNzOjAF4Ie6xRGlFmhQJZrLvgGAIO8Zqg4eFQvFemEM3iEwK6i6l+8wzUj9lu/cTLTqV8aLMOAbcH0KfDPkYTK11OkZpiBpAPfh+BqEY1+ID14nVt+AOlV7PnB6pKKVpNk3Ek8GX/he9pAhYdrbfETaVM6xx4V2heR/tu4MvEfZkfqEsJImy9y6VudHhMhEK76fNX+C4ZsKQFEk4VuAbshaGnDuWKyxtd/XsVBBJioFhwYBYXLeiLeOE07JfMNBM+ViTaMoSC1i9+xL7jt5bBWD/s4GOwW3v4NSRoDuDNYGEc139FIUxbtRsIVty+m8vJNZIJqT7+3mUWhWIa1G5c00IDSvaIOc0BdwH6OFv02/vQbYgj03n36xWtPEOEF6A=
  - secure: VBJmdo89idFJRprW1M+FQm0XkZAj351TOauufz/BSRYeEJ5kVDKkfuywFW2/L1GnG77hU9aJ+U13pZDZW1GCX15JiG+x/bH5hmbcOLl9HJTcijJzrpSeZtuCqI5LRRLjeY2mbj2HyE6EoSxHf17gwL31LJvEkNAr4WR7MAcuov5MxExnunIlP+tAoqqUU5h5yf0VTKZm51haNCRYoTFn5NJKgbUirCtkREFks4d3vKUcKg81nJDhLCtfg7o2up+2URO4WO+njoRrL5doCxQ3pal89gaLIop3i21G2ul8NXaafSsCSbXSoe2LxdrIr9Scugwpe+VV8FE/1+KczFdSlb81bK5pECN7JhubljRUhUqcfE2xRApxNcez4v3G8KC8MDt2Z3VUdffFPw192H3G/WM0CE/7HWoRSgKDyEu6m2SXdFo9Pk0OIVoFJ+9azGtbvHBhqPl6dOZzPHPOh0fWGCw1MTWcnvree5uKfdEcJ50E7PMWjIiCgZkjabKyBEadlhK73pxp+m5oNgzYUfRr6/YEnHTExzEmWdydT2jUNoZB/51JCsj1dxL8Islo11+Jwc5uuRS5zv6gnuvHBQaHJkOdZe+jtxMZbmDwdHIvQ93jtckuk5GKjOS1Dn+dTjGmgvbeJfnDLk/BsZXdTS15txTtjweXpYxHFaXOadtpxJs=
notifications:
  slack:
    secure: 1npn2TEo6mq5mrMd/ChPyPchE9piEJzgNvs15WK6SukquaPWRxBLw6aYaF5XlUv2B/zaEJWr4vgxvmimauIJuIwJvdEgltDSZYxIyolX/7YhnqH5lNsf6hmn+6DIzpyLUJDvsRcUVguxut1vGCWm6891GjsyF92Gxw8xGyIcejOptFBglp5GkMa7IHwpba7Wghvy6m6PGtu8g959US2YK68YeHslsXAytipdGohaan1tHWOQL9d+3X5OAZKLaAVnLqrWtYaUQy0dBW6Hoq8QBLsNHkcvzRp/R1Xy03oowqnxfB/tsnmvgnU4BBrxndqWYlrBj5/bO87wSe5N4C5oMZGCeHNKVsxfWGJXldvC3Zl3xxE7zxna5U3pblCBOzUy9+BWB7dX/5CdKg3IR6dbwRRoWds/cY3hlpSAHU7YDW8thASXq8ml2Tnq75kAHs/gpUFKGnsUNhs3mTLYXILQr4wQda4Qmgijgtl+5bcQ9esDEbe40HeGCfey2fMERDc2jMFIJtKCoQOJyddzybYmYB4Ew6eFlsU3o8Psndf8glfoDsEZy7bYWq8rdc8GZrV4IfIGAM1tIunoEXkDXBZ40FoO4hA12M3C1Lhwo05LPMTThTU+ToPHoYyHk+zKgCfvzR+jl3TBIUlMm3270W3ZHPss4i7Y6E6e5ePu9a/Y4FE=
sudo: required
services:
- docker

script:
- npm test
- if [ "$TRAVIS_BRANCH" == "travis_ssh_deploy" ]; then
    export IMG_VERSION=`node -p -e "require('./package.json').version"`;
    echo "Building $IMG_VERSION";
    npm prune --production;
    docker build -t builditdigital/bookit-server:$IMG_VERSION .;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push builditdigital/bookit-server:$IMG_VERSION;
    docker tag builditdigital/bookit-server:$IMG_VERSION builditdigital/bookit-server:latest;
    docker push builditdigital/bookit-server:latest;
  fi

deploy:
  provider: script
  skip_cleanup: true
  script: chmod 600 ./deploy/ec2/travis && ./deploy/deploy.sh
  on:
    branch: travis_ssh_deploy

# Decrypt deployment key
before_install:
- openssl aes-256-cbc -K $encrypted_2d5b9f764c04_key -iv $encrypted_2d5b9f764c04_iv -in ./deploy/ec2/travis.enc -out ./deploy/ec2/travis -d
