# Build specification for building project under Amazon CodeBuild

version: 0.2
env:
  variables:
    USE_CLOUD: "true"
phases:
  install:
    commands:
      - apt-get update
      - apt-get -y install curl
      - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
      - sudo apt-get install -y nodejs
      - npm --version
      - node --version
      - docker --version
  pre_build:
    commands:
      - echo -n "$CODEBUILD_BUILD_ID" | sed "s/.*:\([[:xdigit:]]\{7\}\).*/\1/" > /tmp/build_id.out
      - printf "%s:%s" "$REPOSITORY_URI" "$(cat /tmp/build_id.out)" > /tmp/build_tag.out
      - printf '{"tag":"%s"}' "$(cat /tmp/build_id.out)" > /tmp/build.json
      - cat /tmp/build_id.out
      - cat /tmp/build_tag.out
      - cat /tmp/build.json
      - npm install
      - $(aws ecr get-login)
  build:
    commands:
      - CLOUD_CONFIG=`aws ssm get-parameters --name CLOUD_CONFIG --with-decryption --output text | cut -f 4`
      - TEST_SECRET=`aws ssm get-parameters --name TEST_SECRET --with-decryption --output text | cut -f 4`
      - npm run test:unit  # temporarily only run unit tests until Azure access is figured out.
#      - npm test
      - npm prune --production
      - docker build --tag "$(cat /tmp/build_tag.out)" .
      - docker build --tag "latest" .
  post_build:
    commands:
      - docker push "$(cat /tmp/build_tag.out)"
artifacts:
  files: /tmp/build.json
  discard-paths: yes
